### ISSUE TITLE
Technical: Movie and Actor are entities. No identifier provided

### ISSUE THREAD

**Issue by sushmitha007** [sivvish/spring-xml-demo#6]
Please add identifiers to both Movie and Actor class.

**Comment by sivvish** [comment]
The Task provided did not require/ask to add the identifiers:

"Actor has two String properties, name and gender, and an age property of type int.
An Actor can be initialized with the three properties via the corresponding setter methods. Use
property based injection in the bean definition file (beans.xml)
Movie “has a” Actor that can be initialized via the corresponding setter method. Use property
based object injection in the bean definition file (beans.xml)"
